# Generated by Django 2.2.4 on 2019-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190827_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='visited_user',
            field=models.ManyToManyField(blank=True, related_name='user_visited', to='accounts.Profile'),
        ),
    ]
