# Generated by Django 2.2.4 on 2019-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_subscription',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
