# Generated by Django 2.1.8 on 2019-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190514_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dates',
            field=models.DateField(blank=True, default='2019-05-14'),
            preserve_default=False,
        ),
    ]
