# Generated by Django 2.1.8 on 2019-05-15 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_actor_likeactor_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='likedirector_users',
            field=models.ManyToManyField(blank=True, related_name='like_directors', to=settings.AUTH_USER_MODEL),
        ),
    ]
