# Generated by Django 2.2.4 on 2019-08-27 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190826_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='visited_user',
            field=models.ManyToManyField(blank=True, related_name='user_visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
