# Generated by Django 2.1.8 on 2019-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
