# Generated by Django 2.1.8 on 2019-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_director_likedirector_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='image_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
